### ISSUE TITLE
I want to share the mod to the Chinese MineCraft forum.

### ISSUE THREAD

**Issue by KuraiMoe** [Lemonszz/trap-expansion-fabric#10]
Hi!I think that this mod is very useful ,so I want to share the mod to the forum “https://www.mcbbs.net” in China.
I will mark out the author‘s name and download link from curseforge.com or my mirror(If I can).
Thank you very much and have a good day!

**Comment by Lemonszz** [comment]
The mod is licensed under the MIT license (https://github.com/Lemonszz/trap-expansion-fabric/blob/master/LICENSE.md) , you are free to repost it. A Curseforge link would be preferred.
