### ISSUE TITLE
Can only place detector in horizontal directions.

### ISSUE THREAD

**Issue by Lemonszz** [Lemonszz/trap-expansion-fabric#12]
Detectors can only be placed in horizontal directions, not up or down.

Code & blockstates support vertical directions and they work with no issues if forced into those directions via debug stick.

**Comment by Shnupbups** [comment]
Oh bugger, I fixed this with the Fans but forgot the Detector. The method for getting the direction had a name change in yarn between 1.14 and 1.15 which caused this, as another method took the old name and it only returns horizontal directions. Will fix ASAP.
